apiVersion: v1
kind: Secret
metadata:
  name: DEFAULT_NAME
  namespace: DEFAULT_NAMESPACE
  labels: {}
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjp7CiAgICAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjp7CiAgICAgICAgICAidXNlcm5hbWUiOiJqc3BydWFuY2Vkb21lIiwKICAgICAgICAgICJwYXNzd29yZCI6Ik1vbG9rb3ZhMzchIiwKICAgICAgICAgICJlbWFpbCI6ImpvbmF0aGFuLnNwcnVhbmNlQGRvbWVuZXR3b3JrLmlvIgogICAgICAgfQogICAgfQp9
type: kubernetes.io/dockerconfigjson
# Example creds:
# {
#     "auths":{
#        "https://index.docker.io/v1/":{
#           "username":"jspruancedome",
#           "password": <password>,
#           "email":"jonathan.spruance@domenetwork.io"
#        }
#     }
# }